Add Hyland as partner
opensearch-project/project-website pull request #1009
Opened 2022-09-17 11:29 UTC by aborroy

### Description
Add Hyland as partner

2022-09-18 08:57 UTC, dtaivpp commented
Hey @aborroy, happy to add this but we first need commits signed with a DCO. Here are a [few tips on retroactively applying a sign off.](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md) Thanks!

2022-09-18 09:19 UTC, aborroy commented
Fixed! Thanks for the hint.

2022-09-19 15:45 UTC, krisfreedain requested changes
small change needed

2022-09-19 15:45 UTC, krisfreedain commented on _partners/hyland.md
> + ---
@aborroy 
Please remove the extra single space at the beginning of lines 2-5 
(Jekyll isn't reading it correctly with that tiny issue) 
thanks

2022-09-26 16:53 UTC, krisfreedain commented
Much better @aborroy - thank you. A couple minor fixes now. 
The image seem to line up better if they're square - see example: 
![Screen Shot 2022-09-26 at 9 51 36 AM](https://user-images.githubusercontent.com/4873623/192335478-7c77e8e0-589e-4a42-bcb9-72fe821e7082.png)

Lastly, please make sure you have DCO sign off on the PR as well - once these two things are done we should be good to go

2022-09-27 09:03 UTC, closed without merging

2022-09-27 09:18 UTC, aborroy commented
Since this one has become a bit messy, I've created a new PR in #1023