Blog: One million entities in one minute
opensearch-project/project-website pull request #1033
Opened 2022-09-29 20:27 UTC by Naarcha-AWS

Signed-off-by: Naarcha-AWS <naarcha@amazon.com>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-09-29 20:49 UTC, brijos commented on _posts/2022-09-30-one-million-enitities-in-one-minute.markdown
> +- naarcha
Please add bpavani and joshtok...Two more authors still need to upload their author cards/photos

2022-10-04 19:33 UTC, krisfreedain requested changes
Two minor edits @Naarcha-AWS 
thanks

2022-10-04 19:33 UTC, krisfreedain commented on _authors/amitgalitz.markdown
> +photo: ‘/assets/media/authors/amitgalitz.jpg’
Please modify ‘/assets/media/authors/amitgalitz.jpg’ to '/assets/media/authors/amitgalitz.jpg' 
(it seems the ‘ was a different character set than ' and was causing the author picture to not display in Jekyll.)

2022-10-04 19:33 UTC, krisfreedain commented on _posts/2022-10-03-one-million-enitities-in-one-minute.markdown
> +date: 2022-10-03
please update to 2022-10-05 as we will work to publish this on Thursday 10/5

2022-10-05 23:40 UTC, Naarcha-AWS commented
@krisfreedain: Should be good to go now.

2022-10-06 00:15 UTC, krisfreedain approved these changes
looks great - thank you @Naarcha-AWS

2022-10-06 00:15 UTC, merged