thud-test blog
opensearch-project/project-website pull request #1142
Opened 2022-11-09 20:35 UTC by hdhalter

Signed-off-by: Heather Halter <hdhalter@amazon.com>

### Description
New blog post
 
### Issues Resolved
#1137

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-11-09 22:30 UTC, alicejw-aws approved these changes
Looks good!

2022-11-09 22:32 UTC, alicejw-aws commented on _authors/hdhalter.markdown
> +linkedin: https://www.linkedin.com/in/heather-halter/
you can also include your github: <username> to link it here too

2022-11-10 16:12 UTC, ariamarble approved these changes
LGTM :)

2022-11-10 18:26 UTC, krisfreedain requested changes
left a couple comments for necessary changes (there's one from Alice as well)

Also, the blog filename cannot start with an underscore - change from "_2022-11-08-thudtest.md"  to  "2022-11-08-thudtest.md"

2022-11-10 18:26 UTC, krisfreedain commented on _posts/_2022-11-08-thudtest.md
> +comments: true
remove this line please

2022-11-10 18:26 UTC, krisfreedain commented on _posts/_2022-11-08-thudtest.md
> +category:
insert line above this with the date we expect to publish - example:

date: 2022-11-10 01:01:01 -0700


Also "category" should be changed to "categories"

2022-11-10 22:48 UTC, alicejw-aws commented
update: we could not gain access rights to make the updates, so we recreated with Kris' updates in this PR: https://github.com/opensearch-project/project-website/pull/1147
Thanks

2022-11-11 07:31 UTC, krisfreedain commented
closing per last comment - taking this forward with PR: https://github.com/opensearch-project/project-website/pull/1147

2022-11-11 07:31 UTC, closed without merging