Switched "ingest" -> "visualize" in reference to the Promethius metrics
opensearch-project/project-website pull request #1172
Opened 2022-11-16 21:26 UTC by dtaivpp

Switched the wording from ingest to visualize to better represent what is possible with Prometheus and OpenSearch Dashboards. 

Signed-off-by: David Tippett <dtip@amazon.com>

### Description
Updated word for technical accuracy. 
 
### Issues Resolved
N/A

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-11-16 21:30 UTC, dtaivpp commented
Ran this by @anirudha  and Nitin to verify that we do not actually ingest the data but just allow users to visualize and they confirmed it.

2022-11-16 21:41 UTC, krisfreedain commented
thanks @dtaivpp - @jhmcintyre can you take a look at this - with your input we'll push out this update quickly.

2022-11-16 21:43 UTC, jhmcintyre commented
LGTM

2022-11-16 23:14 UTC, jhmcintyre approved these changes

2022-11-17 16:44 UTC, krisfreedain requested changes
small spelling fix

2022-11-17 16:46 UTC, dtaivpp commented on _posts/2022-11-15-opensearch-2-4-is-available-today.md
> +With this release, you can now visulize metrics data from the open-source [Prometheus](https://prometheus.io/) monitoring solution as well as from log data aggregated within OpenSearch, unlocking new
oof

2022-11-17 16:53 UTC, krisfreedain approved these changes
thanks @dtaivpp

2022-11-17 16:53 UTC, merged