Release Data Prepper 2.1.0
opensearch-project/project-website pull request #1394
Opened 2023-03-01 20:54 UTC by asifsmohammed

### Description
Releases Data Prepper 2.1.0

The maintainers plan to release 2.1.0 on 03/02/2023. This PR includes the changes for it. Please merge after the release has completed.
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-03-01 22:16 UTC, cmanning09 submitted a review, later dismissed

2023-03-01 22:59 UTC, sshivanii submitted a review, later dismissed

2023-03-02 17:31 UTC, krisfreedain requested changes
@asifsmohammed looks like it's missing the '2023-02-02-opensearch-1.3.8.markdown' with updates for the new data prepper version

2023-03-02 18:03 UTC, krisfreedain approved these changes
looks good - thank you @asifsmohammed

2023-03-02 18:03 UTC, merged