Added Titaniam partner assets
opensearch-project/project-website pull request #140
Opened 2021-06-15 23:19 UTC by makarthikeyan1

### Description
Add Titaniam logo and website link to opensearch partners page
 
### Issues Resolved
None

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2021-06-16 13:57 UTC, stockholmux requested changes
Just a few tweaks.

2021-06-17 00:08 UTC, makarthikeyan1 commented on _partners/titaniam.md
> +# upload your logo to the following directory - must be square
done

2021-06-17 00:08 UTC, makarthikeyan1 commented on _partners/titaniam.md
> +logo: '/assets/media/partners/titaniam.png'
updated. please take a look.

2021-06-17 16:33 UTC, merged

2021-06-17 16:33 UTC, stockholmux commented
This looks great, thanks @makarthikeyan1!