format: add appbase.io to opensearch partners page
opensearch-project/project-website pull request #145
Opened 2021-06-23 11:27 UTC by siddharthlatest

### Description

Adds appbase.io to the opensearch partners page

---

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2021-06-23 13:27 UTC, elfisher commented
This LGTM (screenshot below). @siddharthlatest would you mind switching the branch that you are merging into to `staging`? 

![image](https://user-images.githubusercontent.com/10850824/123104736-355acc00-d405-11eb-8fb8-faea1381ff18.png)

2021-06-23 15:19 UTC, stockholmux requested changes
One small nit with the image.

2021-06-23 15:19 UTC, stockholmux commented on _partners/appbaseio.md
> +logo: '/assets/media/partners/appbase-io.png'
Do you have a transparent background png? It will look cleaner and more consistent.

2021-06-23 16:53 UTC, siddharthlatest commented
@stockholmux @elfisher Thanks, have addressed both parts.

2021-06-23 17:34 UTC, elfisher approved these changes
LGTM

2021-06-24 21:29 UTC, stockholmux commented
Looks great!

2021-06-24 21:29 UTC, merged