Propose a blog post on some performance fixes contributions
opensearch-project/project-website pull request #1520
Opened 2023-04-10 15:51 UTC by chibenwa

### Description

Proposition of blog post based on some performance fixes contribution. Thanks for OpenSearch team for the support doing this.
 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-04-10 22:17 UTC, wbeckler reviewed
This is such an awesome blog post!!!

2023-04-10 22:17 UTC, wbeckler commented on _posts/2023-04-10-opensource-perf.markdown
> +Apache James relies on OpenSearch as its search engine for its email database. It takes as a dependency the [opensearch-java client](https://github.com/opensearch-project/opensearch-java). Performanc
Could you maybe clarify how this was detected? As in, which particular benchmark or analysis revealed this disparity?

2023-04-10 22:17 UTC, wbeckler commented on _posts/2023-04-10-opensource-perf.markdown
> +Flamegraphs are powerful visualization tools that can help developers analyze the execution flow of their code and identify bottlenecks. By analyzing the flamegraphs, I was able to identify specific
```suggestion
Flamegraphs are powerful visualization tools that can help developers analyze the execution flow of their code and identify bottlenecks. By analyzing the flamegraphs, I was able to identify specific areas of code that were causing the performance issue. We used async-profiler to generate a flamegraph and found that frequent SPI lookups were causing the performance issue.
```

2023-04-10 22:17 UTC, wbeckler commented on _posts/2023-04-10-opensource-perf.markdown
> +-   Applicatives calls to the driver from applicative threads (small stacktraces in the center)
I don't think "applicative" is the right word in English, but I'm not sure what is the right word to use.

2023-04-10 22:17 UTC, wbeckler commented on _posts/2023-04-10-opensource-perf.markdown
> +-   Unsurprisingly JSON parsing takes 11% of the drivers CPU and 24% of heap allocation.
```suggestion
-   Unsurprisingly JSON parsing takes 11% of the driver's CPU and 24% of heap allocation.
```

2023-04-10 22:17 UTC, wbeckler commented on _posts/2023-04-10-opensource-perf.markdown
> +As a common practise we then run micro-benchmarks to validate changes, and [JMH](https://github.com/openjdk/jmh) comes in handy for this! It summarizes key metrics, performs warmup, repeats measureme
```suggestion
As a common practice we then run micro-benchmarks to validate changes, and [JMH](https://github.com/openjdk/jmh) comes in handy for this! It summarizes key metrics, performs warmup, repeats measurements and comes with nano-second resolution!
```

2023-04-10 22:18 UTC, dblock reviewed
I like the post! I think it tries a little too much to talk _both_ about the collaborative aspects and about the technical ones. It's a strong technical post! So, I would focus on the technical aspects of the fix 100% until the conclusion, in which your personal comment about collaborating in the open is much appreciated.

2023-04-10 22:18 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +title:  "Collaborating to Improve Open Source Performance: A Case Study"
I appreciate your calling out our collaboration, but you did all the work! I would just call it "Improving JSON parsing performance in opensearch-java" and removing this "dblock" person from the authors!

2023-04-10 22:18 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +meta_description: Learn how key contributors of APache James found out and fixed major performance problems in OpenSearch Java driver.
Apache lowercase P.
Drop "key".
Get specific on what the performance problem was (JSON parsing?)

2023-04-11 08:18 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +  - chibenwa
```suggestion
  - wbeckler
  - chibenwa
```

2023-04-11 08:18 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +meta_description: Learn how key contributors of APache James found out and fixed major performance problems in OpenSearch Java driver.
```suggestion
meta_description: Learn how contributors of Apache James found out and fixed major performance problems in OpenSearch Java driver JSON parsing.
```

2023-04-11 08:19 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +title:  "Collaborating to Improve Open Source Performance: A Case Study"
```suggestion
title:  "Improving JSON parsing performance in opensearch-java"
```

2023-04-11 08:22 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +Apache James relies on OpenSearch as its search engine for its email database. It takes as a dependency the [opensearch-java client](https://github.com/opensearch-project/opensearch-java). Performanc
```suggestion
Apache James relies on OpenSearch as its search engine for its email database. It takes as a dependency the [opensearch-java client](https://github.com/opensearch-project/opensearch-java). We frequently run performance tests with custom [Gatling](https://gatling.io/) made benchmarks. Especially we conducting regression tests on performance when migrating from ElasticSearch 7.10 to OpenSearch for licenses reasons (as an Apache project the SSPL license of driver code is not acceptable). We realized the OpenSearch requests were slower and started investigating why.
```

2023-04-11 08:23 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +-   Applicatives calls to the driver from applicative threads (small stacktraces in the center)
```suggestion
-   Apache James calls to the OpenSearch driver (small stacktraces in the center)
```

2023-04-12 01:35 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +  - wbeckler
As you wish

2023-04-14 20:04 UTC, dblock reviewed
I have some nits, otherwise LGTM!

2023-04-14 20:04 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +As an open source enthusiast, I believe in the power of collaboration to make open source projects faster and more efficient. In this blog post, I will share how my team at [LINAGORA](https://linagor
performance issue in **the OpenSearch Java client**

2023-04-14 20:04 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +As an open source enthusiast, I believe in the power of collaboration to make open source projects faster and more efficient. In this blog post, I will share how my team at [LINAGORA](https://linagor
I would remove "to make the project better" because it dilutes the "identified and addressed a performance issue"

2023-04-14 20:04 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +Apache James relies on OpenSearch as its search engine for its email database. It takes as a dependency the [opensearch-java client](https://github.com/opensearch-project/opensearch-java). We frequen
Maybe soften "SSPL license of driver code is not acceptable" to "we are not permitted to use non-open-source code" or "not allowed to depend on non-APLv2 code"?

2023-04-14 20:04 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +[opensearch_2.4.0.zip](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip) is the flame graph we diagnosed this issue from. Taken with <https://github.com/jvm-p
Make it a full sentence? You can download the flame graph taken with ... in my container ...

2023-04-16 06:28 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +As an open source enthusiast, I believe in the power of collaboration to make open source projects faster and more efficient. In this blog post, I will share how my team at [LINAGORA](https://linagor
```suggestion
As an open source enthusiast, I believe in the power of collaboration to make open source projects faster and more efficient. In this blog post, I will share how my team at [LINAGORA](https://linagora.com), contributing to the Apache James project, identified and addressed a performance issue in the OpenSearch java client using benchmark tools and flamegraphs, and collaborated with the OpenSearch community.
```

2023-04-16 06:30 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +Apache James relies on OpenSearch as its search engine for its email database. It takes as a dependency the [opensearch-java client](https://github.com/opensearch-project/opensearch-java). We frequen
```suggestion
Apache James relies on OpenSearch as its search engine for its email database. It takes as a dependency the [opensearch-java client](https://github.com/opensearch-project/opensearch-java). We frequently run performance tests with custom [Gatling](https://gatling.io/) benchmarks. We specifically wanted to regression test performance when we migrated from ElasticSearch 7.10 to OpenSearch for licenses reasons (as an Apache project, we must use licenses compatible with the Apache License 2.0). We realized the OpenSearch requests were slower and started investigating why.
```

2023-04-16 06:31 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +[opensearch_2.4.0.zip](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip) is the flame graph we diagnosed this issue from. Taken with <https://github.com/jvm-p
```suggestion
[opensearch_2.4.0.zip](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip) is the flame graph we diagnosed this issue from. It was taken with <https://github.com/jvm-profiling-tools/async-profiler>  from within Apache James container):
```

2023-04-19 13:06 UTC, dblock reviewed
Added some nits. I think "collaborated with the community" is giving the community too much credit :) You contributed by fixing a real problem, and thank you!

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +[opensearch_2.4.0.zip](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip) is the flame graph we diagnosed this issue from. It was taken with <https://github.co
I would move the link to the graph below the graph, and maybe make it a full sentence, e.g. `You can download the interactive flame graph that was used to diagnose this issue [here](...).`

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +[opensearch_2.4.0.zip](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip) is the flame graph we diagnosed this issue from. It was taken with <https://github.co
Does the link https://github.com/jvm-profiling-tools/async-profiler work? Maybe just make it `[async-profiler](https://github.com/jvm-profiling-tools/async-profiler)`

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +Then searching for opensearch using the search widget in the top left corner of the flame graph:
opensearch -> quote it since we're talking a string and not the product, "opensearch"

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +Then searching for opensearch using the search widget in the top left corner of the flame graph:
Is it "flamegraph" or "flame graph"? Use the same in the entire post.

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +-   The driver thread (on the right) with the httpclient event loop
If it's a full sentence finish with a period, or lowercase the first word

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +-   We spend a huge amount of resources doing SPI calls in order to locate the JSON parser implementation. It not only eats CPU/heap allocations but it also blocks the HTTP event loop, which can be c
huge amount -> something more specific like a %?

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +To mitigate calls to the SPI, we submitted a [small change](https://github.com/opensearch-project/opensearch-java/pull/293/files) to JsonValueParser.java that addressed the issue. This led to a 50x s
small change -> a change

remove /files from the PR URL

link JsonValueParser.java

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +Here is the JMH output backing this change:
Include how to run the benchmark?

2023-04-19 13:06 UTC, dblock commented on _posts/2023-04-10-opensource-perf.markdown
> +The bench was applied before/after the backport of this PR on top of Apache James CF [apache/james-project@d5af3a5](https://github.com/apache/james-project/commit/d5af3a52cd30eebf7a8fb4d8f2402920c42d
Add a perioid.

2023-04-21 09:46 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +As an open source enthusiast, I believe in the power of collaboration to make open source projects faster and more efficient. In this blog post, I will share how my team at [LINAGORA](https://linagor
```suggestion
As an open source enthusiast, I believe in the power of collaboration to make open source projects faster and more efficient. In this blog post, I will share how my team at [Linagora](https://linagora.com), contributing to the Apache James project, identified and addressed a performance issue in the OpenSearch java client using benchmark tools and flamegraphs, and collaborated with the OpenSearch community.
```

2023-04-21 09:49 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +Then searching for opensearch using the search widget in the top left corner of the flame graph:
```suggestion
Then searching for `"opensearch"` using the search widget in the top left corner of the flamegraph:
```

2023-04-21 09:49 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +-   The driver thread (on the right) with the httpclient event loop
```suggestion
-   The driver thread (on the right) with the httpclient event loop.
```

2023-04-21 09:51 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +To mitigate calls to the SPI, we submitted a [small change](https://github.com/opensearch-project/opensearch-java/pull/293/files) to JsonValueParser.java that addressed the issue. This led to a 50x s
```suggestion
To mitigate calls to the SPI, we submitted a [change](https://github.com/opensearch-project/opensearch-java/pull/293) to [JsonValueParser.java](https://github.com/opensearch-project/opensearch-java/blob/a8df7e7c26ccc644811539c4fea57d97f1031aaa/java-client/src/main/java/org/opensearch/client/json/jackson/JsonValueParser.java#L52) that addressed the issue. This led to a 50x speedup of the JSON parsing by getting rid of the SPI lookups, not even taking into account the blocking operations... Huge win!
```

2023-04-21 10:10 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +-   We spend a huge amount of resources doing SPI calls in order to locate the JSON parser implementation. It not only eats CPU/heap allocations but it also blocks the HTTP event loop, which can be c
```suggestion
-   We spend a huge amount of resources doing SPI calls in order to locate the JSON parser implementation. It not only eats CPU (roughly 26% of driver CPU consumption) /heap allocations.
-   But it also blocks the HTTP event loop, which can be catastrophic: the driver relies on a few thread submitting requests in parallel thus blocking the thread impacts seriously overall latencies and throughput.
```

2023-04-21 10:10 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +[opensearch_2.4.0.zip](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip) is the flame graph we diagnosed this issue from. It was taken with <https://github.co
```suggestion
Here is the flame graph we diagnosed this issue from. It was taken with [async-profiler](https://github.com/jvm-profiling-tools/async-profiler)  from within Apache James container:
```

2023-04-21 10:10 UTC, chibenwa commented on _posts/2023-04-10-opensource-perf.markdown
> +
```suggestion

You can download the interactive flame graph that was used to diagnose this issue [here](https://github.com/opensearch-project/opensearch-java/files/10334079/opensearch_2.4.0.zip).

```

2023-04-21 12:42 UTC, natebower requested changes
@chibenwa I am the editor for the OpenSearch Project. Please see my comments and suggested changes, and let me know if you have any questions or need any clarification. Tag me once you've had a chance to address my comments/changes so I can take a final look, and then we should be good to publish. Thanks!

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +-   Unsurprisingly JSON parsing takes 11% of the driver's CPU and 24% of heap allocation.
```suggestion
-   Unsurprisingly, JSON parsing takes 11% of the driver's CPU and 24% of its heap allocation.
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +-   Event loop busyness (pushing stuff to the kernel network stack, SSL) takes around 60% of the event loop CPU, 25% of heap allocations, which again feels normal to me.
```suggestion
-   Event loop busyness (pushing stuff to the kernel network stack, SSL) takes around 60% of the event loop CPU and 25% of heap allocations, which appears normal.
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +-   Event loop busyness (pushing stuff to the kernel network stack, SSL) takes around 60% of the event loop CPU, 25% of heap allocations, which again feels normal to me.
I would use a word other than "stuff." Can we be more precise?

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +-   2.3% of the event loop CPU is our binding to Reactor reactive library, which, again is normal: converting futures and enqueuing tasks takes time.
```suggestion
-   2.3% of the event loop CPU is our binding to a Reactor reactive library, which, again, is normal: converting futures and enqueuing tasks takes time.
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +Flamegraphs are powerful visualization tools that can help developers analyze the execution flow of their code and identify bottlenecks. By analyzing the flamegraphs, I was able to identify specific
Should we define SPI for readers who may not be familiar?

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +To mitigate calls to the SPI, we submitted a [change](https://github.com/opensearch-project/opensearch-java/pull/293) to [JsonValueParser.java](https://github.com/opensearch-project/opensearch-java/b
```suggestion
To mitigate calls to the SPI, we submitted a [change](https://github.com/opensearch-project/opensearch-java/pull/293) to [JsonValueParser.java](https://github.com/opensearch-project/opensearch-java/blob/a8df7e7c26ccc644811539c4fea57d97f1031aaa/java-client/src/main/java/org/opensearch/client/json/jackson/JsonValueParser.java#L52) that addressed the issue. This led to a 50x speedup of the JSON parsing by getting rid of the SPI lookups, not even taking into account the blocking operations...huge win!
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +Flamegraphs are powerful visualization tools that can help developers analyze the execution flow of their code and identify bottlenecks. By analyzing the flamegraphs, I was able to identify specific
```suggestion
Flame graphs are powerful visualization tools that can help developers analyze the execution flow of their code and identify bottlenecks. By analyzing the flame graphs, we were able to identify specific areas of code that were causing the performance issue. We used async-profiler to generate a flame graph and found that frequent SPI lookups were causing the performance issue.
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +As a common practice we then run micro-benchmarks to validate changes, and [JMH](https://github.com/openjdk/jmh) comes in handy for this! It summarizes key metrics, performs warmup, repeats measureme
```suggestion
As a common practice, we then run micro-benchmarks to validate changes, and [JMH](https://github.com/openjdk/jmh) comes in handy for this. It summarizes key metrics, performs warmup, repeats measurements, and comes with nanosecond resolution!
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +Here is the JMH output backing this change:
```suggestion
Here is the JMH output backing this change.
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +#### Code of the benchmark
"Benchmark code"?

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +### Identifying the performance issue
```suggestion
## Identifying the performance issue
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +### Collaborating with the OpenSearch community
```suggestion
## Collaborating with the OpenSearch community
```

2023-04-21 12:42 UTC, natebower commented on _posts/2023-04-10-opensource-perf.markdown
> +I believe open source projects are more than just code--they're communities of people who share a common goal of making technology more accessible and efficient. By collaborating with the OpenSearch
```suggestion
I believe open-source projects are more than just code---they're communities of people who share a common goal of making technology more accessible and efficient. By collaborating with the OpenSearch community, we contributed to this goal by getting rid of SPI lookups and improving JSON parsing performance in an application that is probably running on countless servers. Working together, we made OpenSearch faster and more efficient. It's rewarding to make a positive impact on both technology and the community of people who use it. This case study shows how collaboration and community involvement can make open-source technology better for everyone.
```

2023-04-25 01:28 UTC, pajuric commented on _posts/2023-04-10-opensource-perf.markdown
> +meta_keywords: OpenSearch, Apache James, Flame graph, Performance, Driver
Keywords are too broad, please update the meta with the following: 

**meta_keywords:** Apache James, flame graph, flamegraph, JSON parsing performance< OpenSearch Java driver

2023-04-25 01:29 UTC, pajuric commented on _posts/2023-04-10-opensource-perf.markdown
> +meta_description: Learn how contributors of Apache James found out and fixed major performance problems in OpenSearch Java driver JSON parsing.
Please use the following meta for the description:

**meta_description:** Learn how Apache James project contributors identified and assessed issues with the OpenSearch Java driver to improve JSON parsing performance.

2023-04-25 01:32 UTC, pajuric commented
@wbeckler - Please advise when the edits have been made, as I have room in the schedule to publish this week.

2023-05-30 15:35 UTC, pajuric commented
@wbeckler - Have the final edits been made and is it ready to publish?

2023-06-05 19:19 UTC, VachaShah commented
> @wbeckler - Have the final edits been made and is it ready to publish?

The final edits are done in PR #1652 since I could not push to this PR. Please let me know if there are any other edits needed.

2023-06-13 15:12 UTC, wbeckler commented
Closing as redundant to https://github.com/opensearch-project/project-website/pull/1652

2023-06-13 15:12 UTC, closed without merging