1854 data prepper 2.4.0 announcement blog
opensearch-project/project-website pull request #1892
Opened 2023-08-19 01:19 UTC by dlvenable

### Description

A blog post announcing the release of Data Prepper 2.4.0
 
### Issues Resolved

Resolves #1854

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-08-22 20:02 UTC, Naarcha-AWS requested changes
I suggested rewrites for each section that make the blog less verbose. Let me know if you have any questions.

2023-08-22 20:02 UTC, Naarcha-AWS commented on _posts/2023-08-17-Announcing-Data-Prepper-2.4.0.md
> +S3 sink codecs
Rewrite for this section:

--- 

Data Prepper 2.4.0 adds new codecs to the [S3 sink](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/s3/):

- **JSON codec**: The JSON codec writes an S3 objects as a valid JSON object and includes all events sent to S3 in the JSON array. This is useful when integrating with systems that expect JSON objects.
- **Arvo codec**: The Arvo codecs gives you the ability to define Arvo schemas and write events in the Arvo format.
- **Parquet codec**: The [Apache Parquet (Parquet)](https://parquet.apache.org/) codec lets you use the Parquet columnar format. By saving you data in the Parquet format, you efficiently retrieve that data at a later time for analysis. You can also define your schema in the Avro format inside the Parquet codec.
- **CSV codec**: The CSV codec allows you to write events in a delimited format, such as TSV or CSV.

The following example configures an Avro codec with a schema for network traffic:

```json
s3:
  codec:
    avro:
      schema: >
        {
          "type" : "record",
          "namespace" : "org.opensearch.dataprepper.examples",
          "name" : "NetworkTraffic",
          "fields" : [
            { "name" : "sourcePort", "type": "int"},
            { "name" : "destinationPort", "type": "int"},
            { "name" : "sourceAddress", "type" : "string"},
            { "name" : "destinationAddress", "type" : "string"},
            { "name" : "bytes", "type": "int"},
          ]
        }
```

Additionally, the S3 sink can now write compressed `gzip` or compressed `snappy` files to reduce your network or storage needs. To use this setting, add the following to your pipeline:

```json
s3:
  compression: gzip
```

2023-08-22 20:02 UTC, Naarcha-AWS commented on _posts/2023-08-17-Announcing-Data-Prepper-2.4.0.md
> +## Streaming anomaly detection with high cardinality
Rewrite here:

--- 

The streaming `anomaly_detector` now contains the `identification_keys` options, which creates a Random Cut Forest (RCF) model for each value in the your time-series data. With the `identification_keys` option, anomalies can be detected in unique set of keys.

The following examples create an `anomaly_detection` processor that detects anomalies for each unique IP address:

```json
processor:
- anomaly_detector:
   identification_keys: ["ip"]
   keys: ["latency"]
   mode:
    random_cut_forest:
```

You can write anomalies detected by the processor to a seperate index and create alerts using [document level monitors](https://opensearch.org/docs/latest/observing-your-data/alerting/api/#document-level-monitors).

Furthermore, you can use the `verbose` configuration in the anomaly detection processor to change the number of alerts and anomalies shown by the processor, `false` for less, `true` for more.

2023-08-22 20:02 UTC, Naarcha-AWS commented on _posts/2023-08-17-Announcing-Data-Prepper-2.4.0.md
> +OpenSearch sink can now write to ElasticSearch 6.8 version. User can specify `distribution_version: "es6"` under OpenSearch sink to write to ES 6.8 versions.
```suggestion
The `opensearch` sink can now write to ElasticSearch 6.8 changing the `distribution_version` setting to `es6`.
```

2023-08-22 20:02 UTC, Naarcha-AWS commented on _posts/2023-08-17-Announcing-Data-Prepper-2.4.0.md
> +Upcoming changes
```suggestion
## Upcoming changes

Future versions of Data Prepper will include:

- A [`geoip` processor](https://github.com/opensearch-project/data-prepper/issues/253) for extracting locations from IP addresses.
- The ability to [migrate](https://github.com/opensearch-project/data-prepper/issues/1985) from older versions of OpenSearch.
- The ability to write to Amazon Simple Notification Service (SNS) using an [SNS sink](https://github.com/opensearch-project/data-prepper/issues/2938).

For a list of more features we plan to include in future releases, see the [project roadmap](https://github.com/opensearch-project/data-prepper/projects/1).
```

2023-08-23 01:07 UTC, pajuric commented on _posts/2023-08-23-Announcing-Data-Prepper-2.4.0.md
> +meta_keywords: Data Prepper 2.4.0
Suggested meta update: 

**meta_keywords:** Data Prepper, Apache Kafka, Amazon S3 bucket, OpenSearch ingestion

**meta_description:** OpenSearch has launched Data Prepper 2.4.0 with feature support for Apache Kafka source, S3 batch processing, filtering in sinks, S3 sink codecs, and high-cardinality anomaly detection.

2023-08-25 18:07 UTC, dlvenable commented on _posts/2023-08-17-Announcing-Data-Prepper-2.4.0.md
> +OpenSearch announces the release of Data Prepper 2.4.0.
I took the suggestion as-is.

2023-08-25 18:33 UTC, dlvenable commented
@Naarcha-AWS , @krisfreedain ,

This has been updated with the requested suggestions, and I have resolved the DCO issue. I've also updated the release date for Monday, Aug 28.

We do also still have to update the "Thank You" text section. I expect to have this by the end of the day.

2023-08-28 19:32 UTC, dlvenable commented
@natebower , @Naarcha-AWS : This PR is updated with corrections to the DCO, requested changes, and the Thank You text.

Data Prepper 2.4.0 is released, so we'd like to get this post out today or tomorrow if possible. Thanks!

2023-08-29 14:53 UTC, Naarcha-AWS approved these changes

2023-08-29 16:02 UTC, natebower requested changes
@dlvenable @Naarcha-AWS Please see my comments and changes and let me know once addressed so that I can approve and push forward. Thanks!

2023-08-29 16:45 UTC, dlvenable commented on _posts/2023-08-28-Announcing-Data-Prepper-2.4.0.md
> +Data Prepper 2.4.0 adds for the S3 scan functionality, which scans Amazon S3 buckets to process existing objects without having to set up Amazon Simple Queue Service (SQS) notifications.
I changed it to use "Amazon S3 Event Notifications" since this is what is being setup with SQS.

2023-08-29 16:49 UTC, dlvenable commented on _posts/2023-08-28-Announcing-Data-Prepper-2.4.0.md
> +* [JonahCalvo](https://github.com/JonahCalvo) - Jonah Calvo
I updated the dashes to en dashes.

However, I'm only using GitHub data for the names. Not all GitHub profiles have names, and that is why they are missing. This was produced via the GitHub API with what was provided.

I could leave it without the name part. Or I could add the GitHub user Id in place of the full name where missing. Do you have any opinions on this?

2023-08-29 16:54 UTC, natebower commented on _posts/2023-08-28-Announcing-Data-Prepper-2.4.0.md
> +* [JonahCalvo](https://github.com/JonahCalvo) - Jonah Calvo
That makes sense, and I think your current approach is probably the right one. Just wanted to flag it in case we had left anything out 😄.

2023-08-29 16:55 UTC, natebower approved these changes
LGTM. @pajuric This is ready to be published. Thanks!

2023-08-29 17:23 UTC, pajuric commented
@nateynateynate @krisfreedain @dtaivpp - Launch blog is ready to publish.

2023-08-29 17:36 UTC, nateynateynate approved these changes
Looks fine to me.

2023-08-29 17:38 UTC, merged