[OSCI]Added my name in osci author Prerana
opensearch-project/project-website pull request #2043
Opened 2023-09-21 16:56 UTC by prerana30

### Description
Adds prerana as a OSCI author to repository.
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-21 17:00 UTC, vchrombie commented
Hey @prerana30, the commit doesn't have it, you can amend the signature by `git commit --amend -s`. And then you can force push it using `git push -f origin chore/prerana-pc-author`.

This should help.

2023-09-21 17:15 UTC, prerana30 commented
> Hey @prerana30, the commit doesn't have it, you can amend the signature by `git commit --amend -s`. And then you can force push it using `git push -f origin chore/prerana-pc-author`.
> 
> This should help.
Thank you it does help.

2023-09-21 22:18 UTC, ashwin-pc requested changes

2023-09-21 22:18 UTC, ashwin-pc commented on _authors/osci_2023/prerana.markdown
> +twitter: <twitter handle without the @>
Can you remove this line if you are not using it?

2023-09-22 01:41 UTC, dtaivpp approved these changes
Looks great!

2023-09-22 01:41 UTC, merged