[OSCI] Added new osci author page (vincentzhao12)
opensearch-project/project-website pull request #2045
Opened 2023-09-21 16:57 UTC by VincentZhao12

### Description

Adds VincentZhao12 as a new OSCI author to the repository
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-21 22:07 UTC, ashwin-pc approved these changes

2023-09-21 22:18 UTC, ashwin-pc requested changes

2023-09-21 22:18 UTC, ashwin-pc commented on _authors/osci_2023/VincentZhao12.markdown
> +twitter: n/a
Can you remove this line?

2023-09-25 06:59 UTC, dtaivpp commented
Hey @VincentZhao12, can you run the following to fix the signoff? Thank you!

1. In your local branch, run: `git rebase HEAD~5 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin vincent-author`

2023-10-19 20:07 UTC, dtaivpp commented
Closing as requested changes were not made and we are past deadlines.

2023-10-19 20:07 UTC, closed without merging