[OSCI] Add new osci author Pranish Dahal
opensearch-project/project-website pull request #2051
Opened 2023-09-21 16:58 UTC by pranishd1

### Description
Added Pranish Dahal (pranishd1) as author for #osci2023
 
### Issues Resolved
Completed Task1 of OSCI_2023

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-21 22:22 UTC, ashwin-pc requested changes

2023-09-21 22:22 UTC, ashwin-pc commented on _authors/osci_2023/pranishd1.markdown
> +github: https://github.com/pranishd1/
```suggestion
pranishd1
```
Can you make this change?

2023-09-22 01:08 UTC, pranishd1 commented on _authors/osci_2023/pranishd1.markdown
> +github: https://github.com/pranishd1/
I've made the changes you requested.

2023-09-22 01:17 UTC, dtaivpp approved these changes
Looks great thank you!

2023-09-22 01:48 UTC, merged