[OSCI] Add willie-the-lord as new author
opensearch-project/project-website pull request #2055
Opened 2023-09-21 17:03 UTC by Willie-The-Lord

### Description

Add willie-the-lord as new author 
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
 
[X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-21 22:24 UTC, ashwin-pc requested changes

2023-09-21 22:24 UTC, ashwin-pc commented on _authors/osci_2023/wiilie_the_lord.markdown
> +twitter:
Can you remove this line?

2023-09-22 01:18 UTC, Willie-The-Lord commented on _authors/osci_2023/wiilie_the_lord.markdown
> +twitter:
Ok no prob.

2023-09-23 19:52 UTC, joshuarrrr approved these changes
LGTM

2023-09-25 07:08 UTC, dtaivpp approved these changes
Looks great!

2023-09-25 07:10 UTC, merged