chore: add profile details
opensearch-project/project-website pull request #2082
Opened 2023-09-21 23:13 UTC by vicradon

### Description
Adds my personal profile details
 
### Issues Resolved
None

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-21 23:42 UTC, ashwin-pc requested changes

2023-09-21 23:42 UTC, ashwin-pc commented on assets/media/authors/vicradon.png
Lets skip the profile picture for now.

2023-09-21 23:42 UTC, ashwin-pc commented on _authors/vicradon.markdown
> +photo: "/assets/media/authors/vicradon.png"
Can you remove this line?

2023-09-22 07:38 UTC, vicradon commented on _authors/vicradon.markdown
> +photo: "/assets/media/authors/vicradon.png"
Done

2023-09-22 12:13 UTC, closed without merging