Feat/profile
opensearch-project/project-website pull request #2143
Opened 2023-09-22 04:24 UTC by kittynglin

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 02:13 UTC, joshuarrrr requested changes
Please move the new file to the `_authors/osci_2023` directory. Otherwise just a couple small changes needed.

2023-09-25 02:13 UTC, joshuarrrr commented on _authors/kittyng.markdown
> +twitter: @kittyngng1
```suggestion
twitter: kittyngng1
```

2023-09-25 02:13 UTC, joshuarrrr commented on _authors/kittyng.markdown
> +short_name:
remove if not needed
```suggestion
```

2023-09-25 07:57 UTC, dtaivpp commented
Hey to fix DCO can you do the following? 

1. In your local branch, run: git rebase HEAD~4 --signoff
2. Force push your changes to overwrite the branch: git push --force-with-lease origin feat/profile

2023-09-25 22:29 UTC, kittynglin commented
Hello!

Thank you for pointing that out! I believe I already did the changes!

Best,

Kitty Ng

On Mon, Sep 25, 2023 at 12:57 AM David Tippett ***@***.***>
wrote:

> Hey to fix DCO can you do the following?
>
>    1. In your local branch, run: git rebase HEAD~4 --signoff
>    2. Force push your changes to overwrite the branch: git push
>    --force-with-lease origin feat/profile
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensearch-project/project-website/pull/2143#issuecomment-1733116807>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5KVYIJ4H4BHCOZJ3AI2H3LX4E2NXANCNFSM6AAAAAA5CQGWTA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-19 20:52 UTC, dtaivpp commented
Closing as we are past deadline and there are outstanding changes.

2023-10-19 20:52 UTC, closed without merging