Feat/shashwat
opensearch-project/project-website pull request #2146
Opened 2023-09-22 04:55 UTC by AwesomeSauce42

### Description
Added New author Shashwat 

### Issues Resolved
N/A
### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 02:20 UTC, joshuarrrr requested changes
@AwesomeSauce42 Please move the new file to the `_authors/osci_2023` directory.

2023-09-25 02:20 UTC, joshuarrrr commented on _authors/shashwat.markdown
> +**Shashwat** loves to play Badminton and chess. Hobbies including playing the guitar and piano. Major interests would inclued watching shows!
A couple minor style fixes:
```suggestion
**Shashwat** loves to play badminton and chess. Hobbies including playing the guitar and piano. Major interests would include watching shows!
```

2023-09-25 08:19 UTC, dtaivpp commented
@AwesomeSauce42 please address Josh's comments and we should be good to go!

2023-09-25 09:35 UTC, AwesomeSauce42 commented
> @AwesomeSauce42 please address Josh's comments and we should be good to go!

Hi sir, I've made the changes mentioned by sir Josh. Please review!

2023-09-26 18:36 UTC, joshuarrrr commented on _authors/osci_2023/shashwat.markdown
> +**Shashwat** loves to play adminton and chess. Hobbies include playing the guitar and piano. My primary interests include watching shows, gaming, and coding!
nit
```suggestion
**Shashwat** loves to play badminton and chess. Hobbies include playing the guitar and piano. My primary interests include watching shows, gaming, and coding!
```

2023-09-27 09:48 UTC, AwesomeSauce42 reviewed
Typo fixed.

2023-10-07 18:49 UTC, AwesomeSauce42 commented
@joshuarrrr could you confirm the changes? Thanks!

2023-10-17 17:01 UTC, joshuarrrr approved these changes
LGTM

2023-10-19 20:17 UTC, dtaivpp approved these changes
Looks good to me!

2023-10-19 20:17 UTC, merged