add profile page of myself
opensearch-project/project-website pull request #2157
Opened 2023-09-22 09:30 UTC by SpecialAir123

### Description
It added my profile
 
### Issues Resolved
N/A

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-22 09:32 UTC, SpecialAir123 commented
I added myself as a new author

2023-09-22 12:34 UTC, cwperks requested changes
Hi @SpecialAir123 , I am seeing an empty file. Did you make sure to add any unstaged changes before committing?

You can check if you have unstaged changes using `git status`

If there is any change to check in then use `git add <filename>` followed by committing and pushing the change.

2023-09-23 22:03 UTC, SpecialAir123 commented
> Hi @SpecialAir123 , I am seeing an empty file. Did you make sure to add any unstaged changes before committing?
> 
> You can check if you have unstaged changes using `git status`
> 
> If there is any change to check in then use `git add <filename>` followed by committing and pushing the change.

I have committed a new version with my file

2023-09-25 08:07 UTC, dtaivpp requested changes

2023-09-25 08:07 UTC, dtaivpp commented on _authors/osci_2023/hongyuankang.markdown
> +**<Hongyuan Kang>** <I am a senior CS student of UC Berkeley>
Can you remove the twitter line and remove the `<>` from your bio? Thank you!

2023-09-26 21:05 UTC, joshuarrrr commented on _authors/osci_2023/hongyuankang.markdown
> +short_name:  Hongyuan
nit
```suggestion
short_name: Hongyuan
```

2023-09-26 21:13 UTC, SpecialAir123 commented on _authors/osci_2023/hongyuankang.markdown
> +short_name:  Hongyuan
I have modified it.

2023-09-26 21:16 UTC, joshuarrrr approved these changes
@SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.

2023-09-26 21:20 UTC, SpecialAir123 commented
> @SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.



> @SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.

I have done that.

2023-09-26 21:25 UTC, SpecialAir123 commented
> @SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.

I got this error when doing the rebase 
"could not apply 24711d43... add new osci author d-wwwang"

2023-09-26 21:29 UTC, joshuarrrr commented
> > @SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.
> 
> I got this error when doing the rebase "could not apply [24711d4](https://github.com/opensearch-project/project-website/commit/24711d43fb583fa5dc7f2c6243d848e86ac6d20e)... add new osci author d-wwwang"

OK, probably the easiest fix here is a soft reset which will squash all you commits into one (which you will sign):
```
git reset --soft HEAD~9 &&
git commit
```

2023-09-26 21:37 UTC, SpecialAir123 commented
> > > @SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.
> > 
> > 
> > I got this error when doing the rebase "could not apply [24711d4](https://github.com/opensearch-project/project-website/commit/24711d43fb583fa5dc7f2c6243d848e86ac6d20e)... add new osci author d-wwwang"
> 
> OK, probably the easiest fix here is a soft reset which will squash all you commits into one (which you will sign):
> 
> ```
> git reset --soft HEAD~9 &&
> git commit
> ```
I dont know why I got so many commits

2023-09-26 21:44 UTC, SpecialAir123 commented
> > > @SpecialAir123 All the commits need a signoff - follow the instructions in https://github.com/opensearch-project/project-website/pull/2157/checks?check_run_id=17157105376 to fix.
> > 
> > 
> > I got this error when doing the rebase "could not apply [24711d4](https://github.com/opensearch-project/project-website/commit/24711d43fb583fa5dc7f2c6243d848e86ac6d20e)... add new osci author d-wwwang"
> 
> OK, probably the easiest fix here is a soft reset which will squash all you commits into one (which you will sign):
> 
> ```
> git reset --soft HEAD~9 &&
> git commit
> ```

I am so sorry but I really dont know what happened.

2023-09-26 21:52 UTC, closed without merging