add Idris author markdown
opensearch-project/project-website pull request #2165
Opened 2023-09-22 13:33 UTC by in-odds

### Description

Adds my personal profile details
 
### Issues Resolved

None

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 02:36 UTC, joshuarrrr requested changes
Remove the `short_name` field. Otherwise looks good.

2023-09-25 02:36 UTC, joshuarrrr commented on _authors/osci_2023/in-odds.markdown
> +short_name:
remove if not needed:
```suggestion
```

2023-09-25 08:14 UTC, dtaivpp commented
Hey @in-odds please review Josh's feedback, thank you!

2023-09-25 10:39 UTC, in-odds commented on _authors/osci_2023/in-odds.markdown
> +short_name:
Hello, okay, thanks

2023-09-25 10:42 UTC, in-odds commented
Hello @dtaivpp I removed short name, can you check it

2023-10-17 19:48 UTC, joshuarrrr approved these changes
LGTM

2023-10-19 20:44 UTC, dtaivpp approved these changes
Looks good!

2023-10-19 20:44 UTC, merged