first opensource commit
opensearch-project/project-website pull request #2174
Opened 2023-09-22 19:43 UTC by archanadubey

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 02:47 UTC, joshuarrrr requested changes
Needs some formatting updates, but otherwise looks good.

2023-09-25 02:47 UTC, joshuarrrr commented on _authors/osci_2023/archanaDu.markdown
> +github: archanadubey
The formatting of this frontmatter section is important:
```suggestion
github: archanadubey
---
```

2023-09-25 02:47 UTC, joshuarrrr commented on _authors/osci_2023/archanaDu.markdown
> +**Archana** have done bachelor and masters but I have a long career gap. I am again trying to reform my career in software enginnering as a java developer. Looking forawrd to get support and guidence
Some spelling and typo suggestions:
```suggestion
**Archana** have done bachelor and masters but I have a long career gap. I am again trying to reform my career in software engineering as a java developer. Looking forward to get support and guidance to achieve my goal. There are a lot of road blocks in the path. I hope opensource experience will clear blocks and I will have smooth journey afterward.
```

2023-09-25 08:18 UTC, dtaivpp commented
@archanadubey please address Josh's comments and we should be good, thank you!

2023-10-19 20:42 UTC, dtaivpp commented
Closing as we are past deadline and there are outstanding changes.

2023-10-19 20:42 UTC, closed without merging