[OSCI] add new author Shatil
opensearch-project/project-website pull request #2194
Opened 2023-09-23 07:15 UTC by ShatilKhan

### Description
[Add new author Shatil]
 
### Issues Resolved
[None]

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 01:43 UTC, joshuarrrr requested changes
@ShatilKhan For now, let's remove the photo. Also, please move the new file to the `_authors/osci_2023` directory.

2023-09-25 17:34 UTC, dtaivpp commented
@ShatilKhan if you address Josh's comments we can merge this soon! Thank you!

2023-09-25 17:42 UTC, ShatilKhan commented
Addressed Guys! @dtaivpp  @joshuarrrr 
Sorry for the delay!

2023-09-26 18:37 UTC, joshuarrrr commented on _authors/osci_2023/shatil.markdown
> +**Shahriar Shatil** Software developer with experience in React & Node.js , looking to make an impact through his contributions to the OpenSearch project.
nit:
```suggestion
**Shahriar Shatil** Software developer with experience in React & Node.js, looking to make an impact through his contributions to the OpenSearch project.
```

2023-10-18 16:55 UTC, joshuarrrr approved these changes
LGTM

2023-10-19 20:37 UTC, dtaivpp approved these changes
Looks good!

2023-10-19 20:37 UTC, merged