add kafka connect to ingest post part 1
opensearch-project/project-website pull request #2198
Opened 2023-09-23 19:38 UTC by jaehyeon-kim

### Description
PR for community blog series.

Ingest data from Kafka into OpenSearch using Kafka Connect
* Part 1 - Local Development
* Part 2 - AWS Deployment

It just includes Part 1 for now for initial discussion. Part 2 will be include shortly after. 

### Issues Resolved
* [Kafka Connect for OpenSearch Integration](https://github.com/opensearch-project/project-website/issues/1882)

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 17:40 UTC, dtaivpp commented
Hello! Can you please do the following to resolve DCO? Thank you!

1. In your local branch, run: `git rebase HEAD~2 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin main`

2023-09-26 08:01 UTC, jaehyeon-kim commented
Part 2 is added.

2023-10-02 21:45 UTC, jaehyeon-kim commented
Hi, any update on this PR?

2023-10-24 23:35 UTC, pajuric commented
Hi @jaehyeon-kim - we need to break this up into two PRs to avoid pushing both Part 1 and Part 2 live at the same time. In the meantime, I have asked PM to review the content.

2023-10-25 19:04 UTC, kkondaka commented on _posts/2023-09-28-Ingest-data-from-Kafka-into-OpenSearch-using-Kafka-Connect-Part-1-Local-Development.markdown
> +When it comes to ingesting data from Apache Kafka into OpenSearch, OpenSearch has a tool called [Data Prepper](https://opensearch.org/docs/latest/data-prepper/index/) and Amazon OpenSearch Service ha
You should probably mention Managed version of Data-Prepper called "OpenSearch Ingestion Service" (https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ingestion.html) in this context?

2023-10-25 22:02 UTC, dlvenable requested changes

2023-12-13 20:09 UTC, pajuric commented
@jaehyeon-kim - checking in on your blog and seeing if you were able to address the comments above?

2024-09-04 22:53 UTC, closed without merging