OSCI: Adds new author jjafarovs
opensearch-project/project-website pull request #2204
Opened 2023-09-24 01:47 UTC by jjafarovs

### Description
Adds new author jjafarovs
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-24 20:38 UTC, dtaivpp requested changes

2023-09-24 20:38 UTC, dtaivpp commented on _authors/osci_2023/jjafarovs.markdown
> +twitter: <twitter handle without the @>
Please remove the `twitter` line and we should be good to go!

2023-09-25 00:10 UTC, jjafarovs reviewed
Deleted twitter line

2023-09-25 17:43 UTC, dtaivpp approved these changes
Looks great!

2023-09-25 17:43 UTC, merged