[OSCI] Adds new author VJoshi380
opensearch-project/project-website pull request #2207
Opened 2023-09-24 04:54 UTC by VJoshi380

### Description
Placing Vedang Joshi in the authors section of the website repository. 

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2023-09-25 01:51 UTC, joshuarrrr requested changes
A couple small suggestions. Otherwise looks good.

2023-09-25 01:51 UTC, joshuarrrr commented on _authors/osci_2023/vedangjoshi.markdown
> +**Vedang Joshi** I love security through obsucrity :O
I'm not sure if the spelling _is_ the joke, but if not:
```suggestion
**Vedang Joshi** I love security through obscurity :O
```

2023-09-25 01:51 UTC, joshuarrrr commented on _authors/osci_2023/vedangjoshi.markdown
> +twitter:
remove these if not needed

```suggestion
```

2023-09-25 17:44 UTC, dtaivpp commented
@VJoshi380 once you address Josh's comments we are good to go, thank you!

2023-09-25 17:58 UTC, VJoshi380 commented
Thanks for letting me know about the issues. I've removed the unused sections and fixed the typo. Let me know if any other fixes need to be made.

2023-10-19 20:34 UTC, dtaivpp approved these changes
Looks good!

2023-10-19 20:34 UTC, merged