CTF event had messaging from OpenSource Connections training.
opensearch-project/project-website pull request #3178
Opened 2024-08-15 17:56 UTC by nateynateynate

### Description
Removes section from CTF page. 
 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2024-08-15 17:58 UTC, nateynateynate commented
Addresses #3175

2024-08-15 20:35 UTC, krisfreedain requested changes
We should not remove the line, we should edit the line. 

Original:
Please note that attendees of the OpenSource Connections training course are subject to the

Updated:
Please note that participants of the Capture the Flag event are subject to the

2024-08-15 22:41 UTC, nateynateynate commented
> We should not remove the line, we should edit the line.
> 
> Original: Please note that attendees of the OpenSource Connections training course are subject to the
> 
> Updated: Please note that participants of the Capture the Flag event are subject to the

Got it. Ready when you are.

2024-08-16 02:11 UTC, krisfreedain approved these changes

2024-08-16 02:12 UTC, merged