Create Mikhail Smelik community member profile
opensearch-project/project-website pull request #3452
Opened 2024-11-14 23:10 UTC by smelik95

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2024-11-14 23:17 UTC, smelik95 commented
Here is my author image

![smelik](https://github.com/user-attachments/assets/b3fa2404-c94f-4a0d-953d-48ccc2a9d8e6)

2024-11-18 16:53 UTC, nateynateynate requested changes
Looks like you're referencing a photo here that isn't part of the PR. Mind adding the photo as part of your commit?

2024-12-10 18:27 UTC, nateynateynate approved these changes

2024-12-10 22:10 UTC, nateynateynate approved these changes

2024-12-10 22:10 UTC, merged