New Connect page & footer change
opensearch-project/project-website pull request #453
Opened 2021-11-08 22:29 UTC by krisfreedain

Signed-off-by: Kris Freedain <freedak@amazon.com>

### Description
Created a new Connect page and modified the footer - allows the community to connect with the project in a number of ways.
 

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2021-11-08 22:31 UTC, krisfreedain commented
@stockholmux & @elfisher - please take a look. thanks

2021-11-10 15:20 UTC, elfisher requested changes
Overall the content looks good. There is some formatting that would help make the page more readable. Let's first start with removing the bullet points and use paragraph formats. I made some recommendations on order so that similar content is grouped together.

2021-11-10 15:20 UTC, elfisher commented on connect.markdown
> +* OpenSearch has [active forums](https://discuss.opendistrocommunity.dev/), which are the fastest way to get help using, troubleshooting, and developing with OpenSearch. As a bonus, questions and dis
Let's format these as paragraphs without bullets. We may even want to add headings.

2021-11-10 15:20 UTC, elfisher commented on connect.markdown
> +* If you want to present or have a question for an upcoming [community meeting](https://opensearch.org/events/), add a comment to the agenda for that meeting.
Let's move this up next to the forum point.

2021-11-10 15:20 UTC, elfisher commented on connect.markdown
> +* To feature a plug-in or project you developed with OpenSearch, add it to the [community projects](https://opensearch.org/community_projects) page with a pull request.
let's move this below the feature request point.

2021-11-10 15:20 UTC, elfisher commented on connect.markdown
> +* Information about using the OpenSearch brand and logo are available on the [Brand Guidelines](https://opensearch.org/brand.html) page.
let's move this below the partner point

2021-11-10 15:20 UTC, elfisher commented on connect.markdown
> +* To report or inquire about a potential security vulnerability, see the [Reporting a Vulnerability guidelines](https://github.com/opensearch-project/.github/blob/main/SECURITY.md).
@stockholmux aside from bolding, what could be done to make the security point more prominent. Moving it to the top?

2021-11-10 17:17 UTC, elfisher commented on _data/footer.yml
> +    title: 'Contact'
I now see why this was changed. My recommendation is "Contact Us"

2021-11-11 21:53 UTC, krisfreedain commented
@elfisher - I've worked through requested updates and pushed the new files up for review/approval. thanks

2021-11-12 14:02 UTC, elfisher approved these changes

2021-11-12 14:03 UTC, elfisher commented
> @elfisher - I've worked through requested updates and pushed the new files up for review/approval. thanks

This LGTM! Approved.

2021-11-15 18:31 UTC, stockholmux approved these changes

2021-11-15 18:31 UTC, merged