Added python opensearch-logger community project
opensearch-project/project-website pull request #473
Opened 2021-11-12 06:11 UTC by vduseev

### Description
Adding the Opensearch logging handler for python as a community project.
 
### Issues Resolved
None

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2021-11-12 14:07 UTC, elfisher requested changes
This LGTM. One minor change requested. Thanks @vduseev

2021-11-12 14:07 UTC, elfisher commented on _community_projects/python-opensearch-logger.md
> +description: Opensearch logger for Python sends standard logs directly to Opensearch. It provides direct and easy to use logging handler. Supports out of the box Python logging.
minor request to use "OpenSearch" casing.

2021-11-12 17:34 UTC, vduseev commented
@elfisher thanks for noticing. My bad, I thought OpenSearch is written like "Opensearch" 😄

2021-11-18 15:10 UTC, elfisher approved these changes
Hi @vduseev thank you for being part of the OpenSearch project and building a Python client library for handling logging! I’m excited to get this project highlighted on the community project page. With that said, I did want to make a note regarding the logo provided as it is not exactly in line with the project brand guidelines. As a best practice to help keep the OpenSearch brand unified and cohesive, the logo should be used in accordance with the guidelines. However, in this case the logo you’ve provided will be permitted, but I will ask that you use it when specifically referencing this Python client library and not the overall project as that may confuse users. Thanks!

2021-11-18 15:11 UTC, elfisher commented
@stockholmux do we have any other website content we aim to release? I wanted to make sure I didn't merge if there was coordination needed.

2021-11-18 20:08 UTC, vduseev commented
@elfisher thank you for accepting the project into the community page. I will make sure to only use logo in reference to this python based logger compatible OpenSearch, not the OpenSearch project as a whole. 

I can also alter the logo by adding something, like an icon in the front, if you think that's a good idea. That would indicate that this is a logger and not the `opensearch-py` library. The current logo is just the OpenSearch logo colored into the python gradient colors.

2021-11-19 14:02 UTC, stockholmux approved these changes
LGTM

2021-11-19 14:05 UTC, stockholmux commented
@vduseev Content is totally fine, however it looks like you didn't do a commit sign off (`git commit ... -s`) to meet the DCO requirement ([good resource if you haven't had to do this before](https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits#answer-15667644)).

2021-11-20 13:58 UTC, vduseev commented
@stockholmux yeah, I didn't fully understand before what sign-off means. I have squashed both commits into one and signed it off using `git --signoff` feature. Hope I did it right :)

2021-11-22 14:35 UTC, stockholmux approved these changes
LGTM

2021-11-22 14:35 UTC, merged

2021-11-22 14:36 UTC, stockholmux commented
@vduseev Thanks! You did it perfectly.

We've merged it into staging and it will go out in our next push live.