Added Snalisys IK/PinYin/Stconvert, Ingester LanguageDetect/OpenNLP, …
opensearch-project/project-website pull request #536
Opened 2021-11-27 14:51 UTC by aparo

…Prometheus Exporter and Learning-To-Tank Plugins

### Description
This pull request will add some of my managed plugins:
* [IK Analysis for OpenSearch](https://github.com/aparo/opensearch-analysis-ik): The IK Analysis plugin integrates Lucene IK analyzer (http://code.google.com/p/ik-analyzer/) into OpenSearch, support customized dictionary. This is a port of [medcl's IK Analysis](https://github.com/medcl/elasticsearch-analysis-ik).
* [OpenNLP Ingest Processor](https://github.com/aparo/opensearch-ingest-opennlp): This processor is doing named/date/location/'whatever you have a model for' entity recognition and stores the output in the JSON before it is being stored. This is a port of [spinscale's ElasticSearch OpenNLP ingest plugin](https://github.com/spinscale/elasticsearch-ingest-opennlp).
* [Langdetect Ingest Processor](https://github.com/aparo/opensearch-ingest-langdetect): Ingest processor doing language detection for fields. Port of https://github.com/spinscale/elasticsearch-ingest-langdetect
* [Pinyin Analysis for OpenSearch](https://github.com/aparo/opensearch-analysis-pinyin): This Pinyin Analysis plugin is used to do conversion between Chinese characters and Pinyin. Port of https://github.com/medcl/elasticsearch-analysis-pinyin
* [Prometheus Exporter Plugin](https://github.com/aparo/opensearch-prometheus-exporter): This is a builtin exporter from OpenSearch to *Prometheus* based on the code of Vincent Van Hollebeke and others at https://github.com/vvanholl/elasticsearch-prometheus-exporter . It collects all relevant metrics and makes them available to Prometheus via the OpenSearch REST API. 
* [Learning to Rank Plugin](https://github.com/aparo/opensearch-learning-to-rank): This is a port of https://github.com/o19s/elasticsearch-learning-to-rank to work with OpenSearch. It's a rewrite of some parts to be able to work with OpenSearch.
* [STConvert Analysis](https://github.com/aparo/opensearch-analysis-stconvert): STConvert is analyzer that convert Chinese characters between Traditional and Simplified. Port of https://github.com/medcl/elasticsearch-analysis-stconvert
 
### Issues Resolved
New plugins.

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2021-11-30 22:55 UTC, stockholmux requested changes
- DCO check is failing, so you'll need to sign off your commits (squash then commit with `-s`)
- A few small changes noted in the review

2021-11-30 22:55 UTC, stockholmux commented on _community_projects/opensearch-prometheus-learning-to-rank.md
> +name: OpenSearch Prometheus Learning to Rank Plugin
**Prometheus** Learning to Rank Plugin?

2021-11-30 22:55 UTC, stockholmux commented on _community_projects/opensearch-analysis-stconvert.md
> +description: STConvert is analyzer that convert Chinese characters between Traditional and Simplified. This is a port of medcl's STConvert Analysis for ElasticSearch (https://github.com/medcl/elastic
typo: 'that convert'-> 'that convert**s**'

2021-11-30 23:02 UTC, stockholmux commented
@elfisher Take a look at this PR. @aparo has included some URLs in the text for the community project descriptions here.

We currently don't support links/markdown in the fields and it might be cleaner if we did. Thoughts @elfisher (and @aparo)?

2021-12-02 15:28 UTC, elfisher commented
> @elfisher Take a look at this PR. @aparo has included some URLs in the text for the community project descriptions here.
> 
> We currently don't support links/markdown in the fields and it might be cleaner if we did. Thoughts @elfisher (and @aparo)?

Agreed. That would be nice. I'll pull this local and post a screenshot so we can discuss here with examples.

2021-12-02 15:33 UTC, elfisher commented
![image](https://user-images.githubusercontent.com/10850824/144452294-1e6a2411-7061-4f72-96fe-edf18d6cc302.png)
Attaching image.

@stockholmux and @aparo is the desire to highlight the URLs or do link text to a url (e.g. `[text](url)`)?

2021-12-02 16:10 UTC, stockholmux commented
Right. I kind of hate seeing raw, unclickable URLs in web browser. It is a bit of a change though and having links can distract from the primary path - getting users to click on the projects, so there is that balance that should be considered.

From a perspective of the site, it's a relatively simple change. It does introduce a slightly larger burden of checking for correctness as you could pass in some HTML that would break the layout.

2021-12-07 17:01 UTC, aparo commented
I'll remove the links. To simplify the life to everyone.

2021-12-07 17:19 UTC, aparo commented on _community_projects/opensearch-prometheus-learning-to-rank.md
> +name: OpenSearch Prometheus Learning to Rank Plugin
Typo in copy, I'll fix it

2023-02-13 18:32 UTC, krisfreedain commented
@aparo - it's been a while - wanted to see if the edits and DCO could be accomplished soon

2023-03-29 23:44 UTC, krisfreedain commented
never heard back.

2023-03-29 23:44 UTC, closed without merging