V1 2 3
opensearch-project/project-website pull request #590
Opened 2021-12-17 21:33 UTC by stockholmux

### Description
- Adds artifact and version metadata for v1.2.3
- Updates blog post 1.2.3
### Issues Resolved

opensearch-project/OpenSearch#1734

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2021-12-17 21:47 UTC, elfisher submitted a review, later dismissed
LGTM!

2021-12-21 20:04 UTC, VijayanB commented on _versions/2021-12-22-opensearch-1.2.3.markdown
> +    version: 7.16.1
```suggestion
    version: 7.16.2
```

2021-12-21 20:04 UTC, VijayanB requested changes
new logstash image is released

2021-12-22 14:48 UTC, elfisher commented
Closing and replacing with https://github.com/opensearch-project/project-website/pull/602/files so that DCO can be properly signed on the Logstash version update commit.

2021-12-22 14:49 UTC, closed without merging