Partner Highlight hidora
opensearch-project/project-website pull request #629
Opened 2022-01-18 17:16 UTC by piellick

### Description
[proposal about Highlighting hidora partner]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-01-21 22:50 UTC, stockholmux requested changes
Hey this looks pretty good but it's pretty hard to review since it's in two PRs. Can you merge them? 

Also you'll need to fix your DCO sign off.

Glad to assist with these things and get this post going - the content looks great!

2022-01-21 22:50 UTC, stockholmux commented on _posts/partners-hidora
> +# Partner Highlight: Enjoy OpenSearch one click installation with Hidora
Can you add the front-matter?   ([You can see how other posts are structured](https://github.com/opensearch-project/project-website/blob/main/_posts/2022-01-21-dashboards-plugins-intro.markdown)).

Example:
```
---
layout: post
title: "Partner Highlight: Enjoy OpenSearch one click installation with Hidora"
authors:
  - piellick 
date: 2022-01-21
categories:
  - partners
twittercard:
  description: "Hidora is an expert in providing custom solutions for all sizes of businesses. Hidora Cloud Hosting Solutions are just what you need if you want an efficient, secure and scalable cloud hosting solution that is tailored to your needs. We offer different plans that are scalable according to your specific requirements so you can find one that suits you best. Our PaaS help developers to host their applications in few minutes with DevOps philosophy."
---
```

2022-01-21 22:50 UTC, stockholmux commented on _posts/partners-hidora
> +# Partner Highlight: Enjoy OpenSearch one click installation with Hidora
Also, you need an author bio in another file ([example](https://github.com/opensearch-project/project-website/blob/main/_authors/andhopp.markdown))

2022-01-21 22:50 UTC, stockholmux commented on _posts/partners-hidora
> +![](https:///image.png)
- Can you merge this with #633 so we can see your photos in place?
- Each image needs a `{: .img-fluid}` at the end of the line. That will make it work on mobile

2022-01-26 16:08 UTC, piellick commented
Hello @stockholmux , i close this one too .

2022-01-26 16:08 UTC, closed without merging