Add odbc and jdbc 1.1.0.1 release artifact
opensearch-project/project-website pull request #635
Opened 2022-01-19 22:23 UTC by joshuali925

Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description
Add sql-odbc and sql-jdbc drivers to `_artifacts` for their 1.1.0.1 release
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-01-19 23:11 UTC, stockholmux requested changes
A few little issues in the code review. In addition all the artifact filenames start with `_` which makes them hidden from rendering, so those will need to be removed (e.g. `_opensearch-jdbc-1.1.0.1.markdown ` -> `opensearch-jdbc-1.1.0.1.markdown`)

2022-01-19 23:11 UTC, stockholmux commented on _artifacts/opensearch-drivers/_opensearch-jdbc-1.1.0.1.markdown
> +platform: all
`platform` should be `java`

2022-01-19 23:11 UTC, stockholmux commented on _artifacts/opensearch-drivers/_opensearch-jdbc-1.1.0.1.markdown
> +architecture: all
`architecture` should be `jvm`

2022-01-19 23:15 UTC, joshuali925 commented
> A few little issues in the code review. In addition all the artifact filenames start with `_` which makes them hidden from rendering, so those will need to be removed (e.g. `_opensearch-jdbc-1.1.0.1.markdown ` -> `opensearch-jdbc-1.1.0.1.markdown`)

Thanks! updated

2022-01-20 22:15 UTC, stockholmux approved these changes
LGTM!

2022-01-20 22:15 UTC, merged

2022-01-20 22:16 UTC, stockholmux commented
Fixes #429 , unblocks #431

2022-01-20 22:17 UTC, stockholmux commented
@joshuali925 thanks for the contribution. It will go out on next deployment. Once I resolve #431, it will go on the downloads page.