Adds roadmap blog
opensearch-project/project-website pull request #676
Opened 2022-02-10 01:44 UTC by elfisher

### Description
Adds a blog to highlight the proposed release schedule updates

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-02-10 01:45 UTC, elfisher commented
@stockholmux I did this off of main, but there seems to be a ton of commits. Should this be based off of the prod branch?

2022-02-10 14:13 UTC, stockholmux commented
@elfisher It _realllllly_ looks like you made a branch off of `prod` and tried to push it into `main`. If you look at any of the commits that got pulled in they are just the merge commits that are used to trigger a production build.

I could go forward from here as these commits don't change anything but it's overwhelmed the DCO checker as it can't accept this many commits at once 😂... never seen that before!

I would just close the commit out, sync your main branch with the remote main branch and make you single file change and do another commit.

2022-02-10 14:38 UTC, elfisher commented
> @elfisher It _realllllly_ looks like you made a branch off of `prod` and tried to push it into `main`. If you look at any of the commits that got pulled in they are just the merge commits that are used to trigger a production build.
> 
> I could go forward from here as these commits don't change anything but it's overwhelmed the DCO checker as it can't accept this many commits at once 😂... never seen that before!
> 
> I would just close the commit out, sync your main branch with the remote main branch and make you single file change and do another commit.

Sounds good! I'll give that a go and push that up accordingly.

2022-02-21 16:21 UTC, elfisher commented
@stockholmux would it work to publish this tomorrow (02/22)?

2022-02-22 16:37 UTC, stockholmux requested changes
Comments inline for markup and grammar edits.

I generally like the post. For content, I think one thing might be a bit odd. We talk about 'SemVer' and then two points later we talk about tent pole for major versions. Those aren't incompatible, but it's an incomplete picture. In SemVer major versions also represent oopsies - something we may have to fix that change the API. From the description in this blog post, it's not entirely clear that this could happen. Very real possibilities exist that we could rev a major version without these tent-pole features (example: zero day in Node.js that could only be resolved with a change to a new Node.js major would result in a major version rev, as an example).

2022-02-22 16:37 UTC, stockholmux commented on _posts/2022-02-09-roadmap-proposal.md
> +Lucene 9.0.0 [released](https://lucene.apache.org/core/corenews.html#apache-lucenetm-900-available) on December 7, 2021. It includes several new features and performance improvements we would like to
'java jigsaw' -> 'Java Jigsaw'

2022-02-25 19:22 UTC, stockholmux approved these changes
LGTM - I'll change the date on the backend.

2022-02-25 19:22 UTC, merged