Add blog post for Fluent Bit
opensearch-project/project-website pull request #734
Opened 2022-03-22 05:01 UTC by brijos

Signed-off-by: Joshua Bright <jdbright@amazon.com>

### Description
[Added Fluent Bit 1.9 blog post]
 
### Issues Resolved
[[List any issues this PR will resolve](https://github.com/opensearch-project/project-website/issues/733)]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-03-22 15:03 UTC, stockholmux requested changes
Content seems fine. Spacing is causing some rendering chaos.

2022-03-22 15:03 UTC, stockholmux commented on _posts/2022-03-24-getting-started-with-fluent-bit-and-opensearch.md
> + Within a few minutes we should be able to see the CPU metrics under the my_index index within OpenSearch.
"my_index" should be in backticks

2022-03-22 15:09 UTC, brijos commented on _posts/2022-03-24-getting-started-with-fluent-bit-and-opensearch.md
> + Within a few minutes we should be able to see the CPU metrics under the my_index index within OpenSearch.
Corrected!

2022-03-22 15:10 UTC, brijos commented on _posts/2022-03-24-getting-started-with-fluent-bit-and-opensearch.md
> + In this Getting Started Guide we cover 1) the new plugin with integration to OpenSearch, 2) a deployment scenario on top of Kubernetes, and 3) a bonus using some of Fluent Bit’s new 1.9 features.
For the sake of consistency, I'll adjust it.  Thanks!

2022-03-24 15:28 UTC, stockholmux commented
FWIW, we just need one more set of eyes (in process) before we can push this live.

2022-03-24 16:27 UTC, merged