Add Prometheus exporter plugin for OpenSearch
opensearch-project/project-website pull request #750
Opened 2022-04-01 12:10 UTC by lukas-vlcek

Prometheus logo source: https://www.linuxfoundation.org/prometheus-2/

Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-04-04 21:28 UTC, stockholmux requested changes
Awesome contribution (more so the exporter than this YML :) )

A couple of small changes.

2022-04-04 21:28 UTC, stockholmux commented on _community_projects/prometheus-exporter-plugin.md
> +icon: '/assets/media/community_projects/prometheus.svg'
You can also remove the SVG file.

2022-04-05 07:10 UTC, lukas-vlcek commented on _community_projects/prometheus-exporter-plugin.md
> +icon: '/assets/media/community_projects/prometheus.svg'
Done.

2022-04-05 07:11 UTC, lukas-vlcek commented on _community_projects/prometheus-exporter-plugin.md
> +description: The Prometheus® exporter plugin for OpenSearch® exposes many OpenSearch metrics in Prometheus format.
Done.

2022-04-05 07:13 UTC, lukas-vlcek commented
PR updated. Thanks!

2022-04-05 16:34 UTC, merged

2022-04-05 17:27 UTC, lukas-vlcek commented
Thanks @stockholmux