Add stellar cyber partner
opensearch-project/project-website pull request #814
Opened 2022-05-17 15:09 UTC by sjones100

### Description
Added Stellar Cyber as partner
 
### Issues Resolved
N/A

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-05-17 17:18 UTC, krisfreedain requested changes
@sjones100 - small change needed

2022-05-17 17:18 UTC, krisfreedain commented on _partners/stellar-cyber.md
> +logo: '/assets/media/partners/stellar-cyber.png'
Hello @sjones100 - small edit needed - the logo png needs to be square

2022-05-19 17:47 UTC, krisfreedain commented
Hello @sjones100 - changes look good. However, you need to fix the DCO on your commit for this to progress forward https://github.com/opensearch-project/project-website/pull/814/checks?check_run_id=6475852461

2022-05-19 22:14 UTC, sjones100 commented
@krisfreedain apologies, just rebased and fixed, looks like DCO check has passed now

2022-05-20 00:44 UTC, merged

2022-05-20 00:59 UTC, krisfreedain commented
thanks @sjones100 - glad to add you to the partners page! https://opensearch.org/partners/