Adding security issue response blogpost
opensearch-project/project-website pull request #993
Opened 2022-09-13 11:54 UTC by davidlago

Signed-off-by: Dave Lago <davelago@amazon.com>

### Description
A short blogpost to announce the PR about the new security issue response process.
 
### Issues Resolved
Closes #983 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-09-13 13:34 UTC, natebower reviewed
@davidlago Please see my comments and let me know if you have any questions. Thanks!

2022-09-13 13:34 UTC, natebower commented on _posts/2022-09-16-security-issue-response.md
> +title:  "Documenting our Security Issue Response Process"
Sentence case: Documenting our security issue response process

2022-09-13 13:34 UTC, natebower commented on _posts/2022-09-16-security-issue-response.md
> +Today we are taking the next step in our open source journey by updating our security policy to include a process for how we respond to security issues. In proper open source fashion, we are creating
Hyphenate both instances of "open-source". Add a comma after the parenthetical.

2022-09-13 13:34 UTC, natebower commented on _posts/2022-09-16-security-issue-response.md
> +Besides making it transparent what the process looks like for responding to these issues, this policy has a significant addition: **the creation of a pre-disclosure list**.
Change to "Besides making the security issue response process transparent..."

2022-09-13 13:34 UTC, natebower commented on _posts/2022-09-16-security-issue-response.md
> +Having a pre-disclosure list (a group of individuals and companies that will be informed of a security issue before it becomes public) is a risk balancing act. If a security issue gets pre-disclosed
Change "gets" to "is". Change "collaborations to" to "collaborations that would".

2022-09-13 13:34 UTC, natebower commented on _authors/davidlago.markdown
> +**Dave Lago** is a Software Development Manager at AWS working on the OpenSearch project.
This might be smoother as "Dave Lago is an AWS Software Development Manager working on the OpenSearch project."

2022-09-13 13:40 UTC, davidlago commented
@natebower comments addressed. Thanks!

2022-09-13 14:22 UTC, davidlago commented
FYI this PR is not to be merged until the related PR is posted and I update the link here.

2022-09-16 15:09 UTC, davidlago commented
Good to merge! Linked PR has been posted and the text updated with the link 👍

2022-09-16 18:04 UTC, krisfreedain requested changes
@davidlago - one tiny change required

2022-09-16 18:04 UTC, krisfreedain commented on _authors/davidlago.markdown
> +photo: '/assets/media/authors/davidlago.jpg'
looks like this should be .png instead of .jpg

2022-09-16 18:14 UTC, merged